
- platform: workday
  country: US
  province: MI
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]

- platform: template
  sensors:
    dryer_state:
      friendly_name: "Dryer State"
      device_class: running
      value_template: >-
        {% if is_state('sensor.dryer_sensor', 'Running')   %}
          on
        {% else %}
          off
        {% endif %}

- platform: template
  sensors:
    washer_state:
      friendly_name: "Washer State"
      device_class: running
      value_template: >-
        {% if is_state('sensor.washer_state', 'Washing')   %}
          on
        {% else %}
          off
        {% endif %}

