

- platform: decora_wifi
  username: !secret leviton_username
  password: !secret leviton_password

- platform: group
  name: Dressers
  entities:
    - light.dresser1
    - light.dresser2

- platform: group
  name: Living Room Lights
  entities:
    - light.dan_lamp
    - light.kelly_lamp
    - light.dining_room_light
    - light.stairway_light

- platform: group
  name: Office Lights
  entities:
    - light.shellydimmer2_e8db84d4610a
    - light.office_desk_lamp
    - light.office_chair_light
    - light.office_window_light

- platform: group
  name: master_bedroom
  entities:
    - light.dan_bedside_lamp
    - light.kelly_bedside_lamp
    - light.dresser1
    - light.dresser2
    - light.master_closet_light

- platform: group
  name: office_others
  entities:
    - light.office_chair_light
    - light.office_window_light


- platform: switch
  name: Candle Mold Light
  entity_id: switch.candle_mold_light_switch
