

- platform: decora_wifi
  username: !secret leviton_username
  password: !secret leviton_password

- platform: switch
  name: Laundry Light
  entity_id: switch.laundry_light

- platform: switch
  name: Coat Rack Light
  entity_id: switch.coat_rack_light

- platform: switch
  name: Deck Light
  entity_id: switch.deck_light

- platform: switch
  name: Woodpile Lights
  entity_id: switch.woodpile_lights

- platform: switch
  name: Path Lights
  entity_id: switch.shelly1l_f4cfa2e397de

#---------------------------------------------------------------------------------------------------------------------#


- platform: group
  name: laundry_lights
  unique_id: laundry_lights
  entities:
    - light.laundry_light
    - light.coat_rack_light

- platform: group
  name: kitchen_lights
  unique_id: Kitchen Lights
  entities:
    - light.kitchen_light
    - light.sink_light

- platform: group
  name: kit_laun_lights
  entities:
    - light.laundry_light
    - light.coat_rack_light
    - light.kitchen_light
    - light.sink_light

- platform: group
  name: outdoor_lights
  unique_id: Outdoor Lights
  entities:
    - light.deck_light
    - light.garage_door_lights
    - light.woodpile_lights
    - light.front_porch_light
    - light.path_lights
