
- platform: hue
  host: !secret hue_host

- platform: decora_wifi
  username: !secret leviton_username
  password: !secret leviton_password

- platform: group
  name: Dressers
  entities:
    - light.dresser1
    - light.dresser2

####  LED Mirror
# - platform: mqtt
#   name: LED Mirror
#   schema: json
#   brightness: true
#   rgb: true
#   white_value: true
#   effect: true
#   effect_list: ["Random","Strobe","Flicker","Presets","None"]
#   state_topic: led_mirror/light/led_mirror/state
#   command_topic: led_mirror/light/led_mirror/command

####  TV Backlight
# - platform: mqtt
#   name: TV Backlight
#   schema: json
#   brightness: true
#   rgb: true
#   effect: true
#   effect_list: :["Color Wipe","Rainbow","Random","Scan","Strobe","Color Strobe","Candy Cane","Wheel of Color","Vesuvius","Theater Marquee","Subway Car","Squeeze","None"]
#   state_topic: tv_backlight/light/tv_backlight/state
#   command_topic: tv_backlight/light/tv_backlight/command