

- platform: tts
  name: kitchen
  tts_service: tts.google_translate_say
  media_player: media_player.kitchen_speaker

- platform: tts
  name: dan
  tts_service: tts.google_translate_say
  media_player: media_player.dan_speaker

- platform: tts
  name: guest
  tts_service: tts.google_translate_say
  media_player: media_player.nestmini4000

- platform: tts
  name: family
  tts_service: tts.google_translate_say
  media_player: media_player.nestmini5470

- platform: tts
  name: office
  tts_service: tts.google_translate_say
  media_player: media_player.office_home

- platform: tts
  name: master
  tts_service: tts.google_translate_say
  media_player: media_player.smart_clock

- platform: tts
  name: spare
  tts_service: tts.google_translate_say
  media_player: media_player.spare_room_speaker



- platform: tts
  name: workshop
  tts_service: tts.google_translate_say
  media_player: media_player.workshop_speaker

- platform: group
  name: all_speakers
  services:
    - service: kitchen
    - service: dan
    - service: guest
    - service: family
    - service: office
    - service: master
    - service: spare
    - service: workshop

- platform: group
  name: no_bedrooms
  services:
    - service: kitchen
    - service: dan
    - service: family
    - service: office
    - service: workshop

- platform: group
  name: bedrooms
  services:
    - service: master
    - service: spare
    - service: guest

- platform: tts
  name: kitchen_cloud
  tts_service: tts.cloud_say
  media_player: media_player.kitchen_speaker

- platform: tts
  name: dan_cloud
  tts_service: tts.cloud_say
  media_player: media_player.dan_speaker

- platform: tts
  name: guest_cloud
  tts_service: tts.cloud_say
  media_player: media_player.nestmini4000

- platform: tts
  name: family_cloud
  tts_service: tts.cloud_say
  media_player: media_player.nestmini5470

- platform: tts
  name: office_cloud
  tts_service: tts.cloud_say
  media_player: media_player.office_home

- platform: tts
  name: master_cloud
  tts_service: tts.cloud_say
  media_player: media_player.smart_clock

- platform: tts
  name: spare_cloud
  tts_service: tts.cloud_say
  media_player: media_player.spare_room_speaker

- platform: tts
  name: workshop_cloud
  tts_service: tts.cloud_say
  media_player: media_player.workshop_speaker

- platform: group
  name: living_room
  services:
    - service: dan

- platform: group
  name: living_room_cloud
  services:
    - service: dan_cloud

- platform: group
  name: all_speakers_cloud
  services:
    - service: kitchen_cloud
    - service: dan_cloud
    - service: guest_cloud
    - service: family_cloud
    - service: office_cloud
    - service: master_cloud
    - service: spare_cloud
    - service: workshop_cloud

- platform: group
  name: no_bedrooms_cloud
  services:
    - service: kitchen_cloud
    - service: dan_cloud
    - service: family_cloud
    - service: office_cloud
    - service: workshop_cloud

- platform: group
  name: bedrooms_cloud
  services:
    - service: master_cloud
    - service: spare_cloud
    - service: guest_cloud

- platform: group
  name: mobile_devices
  services:
    - service: mobile_app_daniels_ipad
    - service: mobile_app_iphone
    - service: mobile_app_sm_s916u
