

- platform: tts
  name: kitchen
  tts_service: tts.google_translate_say
  media_player: media_player.kitchen_speaker

- platform: tts
  name: living_room
  tts_service: tts.google_translate_say
  media_player: media_player.living_room_speaker

- platform: tts
  name: guest
  tts_service: tts.google_translate_say
  media_player: media_player.guest_room_speaker

- platform: tts
  name: family
  tts_service: tts.google_translate_say
  media_player: media_player.family_room_speaker

- platform: tts
  name: office
  tts_service: tts.google_translate_say
  media_player: media_player.office_speaker

- platform: tts
  name: master
  tts_service: tts.google_translate_say
  media_player: media_player.master_bedroom_clock

- platform: tts
  name: spare
  tts_service: tts.google_translate_say
  media_player: media_player.spare_room_speaker

- platform: tts
  name: workshop
  tts_service: tts.google_translate_say
  media_player: media_player.workshop_speaker

- platform: group
  name: all_speakers
  services:
    - service: kitchen
    - service: living_room
    - service: guest
    - service: family
    - service: office
    - service: master
    - service: spare
    - service: workshop

- platform: group
  name: no_bedrooms
  services:
    - service: kitchen
    - service: living_room
    - service: family
    - service: office
    - service: workshop

- platform: group
  name: bedrooms
  services:
    - service: master
    - service: spare
    - service: guest

- platform: tts
  name: kitchen_cloud
  tts_service: tts.cloud_say
  media_player: media_player.kitchen_speaker

- platform: tts
  name: living_room_cloud
  tts_service: tts.cloud_say
  media_player: media_player.living_room_speaker

- platform: tts
  name: guest_cloud
  tts_service: tts.cloud_say
  media_player: media_player.guest_room_speaker

- platform: tts
  name: family_cloud
  tts_service: tts.cloud_say
  media_player: media_player.family_room_speaker

- platform: tts
  name: office_cloud
  tts_service: tts.cloud_say
  media_player: media_player.office_speaker

- platform: tts
  name: master_cloud
  tts_service: tts.cloud_say
  media_player: media_player.master_bedroom_clock

- platform: tts
  name: spare_cloud
  tts_service: tts.cloud_say
  media_player: media_player.spare_room_speaker

- platform: tts
  name: workshop_cloud
  tts_service: tts.cloud_say
  media_player: media_player.workshop_speaker

- platform: group
  name: all_speakers_cloud
  services:
    - service: kitchen_cloud
    - service: living_room_cloud
    - service: guest_cloud
    - service: family_cloud
    - service: office_cloud
    - service: master_cloud
    - service: spare_cloud
    - service: workshop_cloud

- platform: group
  name: no_bedrooms_cloud
  services:
    - service: kitchen_cloud
    - service: living_room_cloud
    - service: family_cloud
    - service: office_cloud
    - service: workshop_cloud

- platform: group
  name: bedrooms_cloud
  services:
    - service: master_cloud
    - service: spare_cloud
    - service: guest_cloud

- platform: group
  name: main_floor_cloud
  services:
    - service: kitchen_cloud
    - service: living_room_cloud
    - service: office_cloud

- platform: group
  name: mobile_devices
  services:
    - service: mobile_app_iphone
    - service: mobile_app_sm_s936u
