

- id: mb_ac_to_night
  alias: MB AC to night
  trigger:
    platform: time_pattern
    hours: 20
    minutes: 00
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.mb_ac_power
        state: 'on'
      - condition: state
        entity_id: input_boolean.ac_automations
        state: "on"
  action:
    - service: script.turn_on
      data:
        entity_id: script.mb_ac_to_night_setting


- id: mb_ac_to_day
  alias: MB AC to day
  trigger:
    platform: time_pattern
    hours: 8
    minutes: 00
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.mb_ac_power
        state: 'on'
      - condition: state
        entity_id: input_boolean.ac_automations
        state: "on"
  action:
    - service: script.turn_on
      data:
        entity_id: script.mb_ac_to_day_setting

- id: lr_ac_powerful_off
  alias: LR AC Powerful Off
  trigger:
    platform: state
    entity_id: switch.lr_powerful
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 3
  action:
    - service: switch.turn_off
      entity_id: switch.lr_powerful

- id: mb_ac_powerful_off
  alias: MB AC Powerful Off
  trigger:
    platform: state
    entity_id: switch.mb_powerful
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 3
  action:
    - service: switch.turn_off
      entity_id: switch.mb_powerful


- alias: 'Dryer has stopped'
  trigger:
    - platform: state
      entity_id: sensor.dryer_sensor
      from: 'Running'
      to: 'Cycle Complete'
      for:
        hours: 0
        minutes: 0
        seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.tts_automations
    state: "on"
  action:
    - service: tts.google_translate_say
      entity_id:
        - media_player.dan_speaker
        - media_player.spare_room_speaker
        - media_player.guest_room_speaker
        - media_player.kitchen_speaker
        - media_player.office_home
        - media_player.kelly_home
        - media_player.smart_clock
      data:
        message: >
          {{
            [
              "The dryer has stopped",
              "Better get those clothes out beofre they wrinkle",
              "Dryer! Now!",
              "No more tumbling",
              "The clothing dehydration process has terminated"
            ] | random
          }}


- alias: 'Laundry sink level high'
  trigger:
    platform: state
    entity_id: binary_sensor.high_water
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  condition:
    - condition: state
      entity_id: script.water_warning
      state: 'off'
  action:
  - service: script.turn_on
    entity_id: script.water_warning
  - service: light.turn_on
    entity_id: light.clock_circle
    data:
      effect: 'Police 3'
      brightness: 255
  - service: light.turn_on
    entity_id: light.wall_clock
    data:
      effect: 'Police 3'
      brightness: 255

- alias: 'Laundry sink level back to normal'
  trigger:
    platform: state
    entity_id: binary_sensor.high_water
    from: 'on'
    to: 'off'
    for:
      seconds: 5
  condition:
    - condition: state
      entity_id: script.water_warning
      state: 'on'
  action:
  - service: script.turn_off
    entity_id: script.water_warning
  - service: light.turn_on
    entity_id: light.clock_circle
    data:
      effect: 'Clock'
  - service: light.turn_on
    entity_id: light.wall_clock
    data:
      effect: 'Clock'

- alias: Washer Start

  trigger:
    platform: numeric_state
    entity_id: switch.washer
    value_template: '{{ states.sensor.washer_current | float }}'
    above: 0.03
    for:
      hours: 0
      minutes: 0
      seconds: 10

  condition:
    - condition: state
      entity_id: input_boolean.washer_status
      state: 'off'

  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.washer_status


- alias: Washer Stop

  trigger:
    platform: numeric_state
    entity_id: switch.washer
    value_template: '{{ states.sensor.washer_current | float }}'
    below: 0.03
    for:
      hours: 0
      minutes: 2
      seconds: 30

  condition:
    - condition: state
      entity_id: input_boolean.washer_status
      state: 'on'

  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.washer_status

- alias: 'Washer has stopped'
  trigger:
    - platform: state
      entity_id: input_boolean.washer_status
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.tts_automations
    state: "on"
  action:
    - service: tts.google_translate_say
      entity_id:
        - media_player.dan_speaker
        - media_player.spare_room_speaker
        - media_player.guest_room_speaker
        - media_player.kitchen_speaker
        - media_player.office_home
        - media_player.kelly_home
        - media_player.smart_clock
      data:
        message: >
          {{
            [
              "The washer has stopped",
              "Finally!  That noise was driving me crazy!",
              "I have had it with these mother fucking clothes in this mother fucking washer",
              "Better get those clothes into the dryer",
              "Done washing"
            ] | random
          }}




# - alias: 'Roomba Bin Full'
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.roomba_bin_full
#       from: 'off'
#       to: 'on'
#       for:
#         hours: 0
#         minutes: 0
#         seconds: 0
#   action:
#     - service: tts.google_translate_say
#       entity_id:
#         - media_player.main_floor
#       data:
#         message: 'The Roomba bin is full'

