

- alias: 'Laundry sink level high'
  trigger:
    platform: state
    entity_id: binary_sensor.high_water
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  condition:
    - condition: state
      entity_id: script.water_warning
      state: 'off'
  action:
  - service: script.turn_on
    entity_id: script.water_warning
  - service: light.turn_on
    entity_id: light.clock_circle
    data:
      effect: 'Police 3'
      brightness: 255
  - service: light.turn_on
    entity_id: light.wall_clock
    data:
      effect: 'Police 3'
      brightness: 255

- alias: 'Laundry sink level back to normal'
  trigger:
    platform: state
    entity_id: binary_sensor.high_water
    from: 'on'
    to: 'off'
    for:
      seconds: 5
  condition:
    - condition: state
      entity_id: script.water_warning
      state: 'on'
  action:
  - service: script.turn_off
    entity_id: script.water_warning
  - service: light.turn_on
    entity_id: light.clock_circle
    data:
      effect: 'Clock'
  - service: light.turn_on
    entity_id: light.wall_clock
    data:
      effect: 'Clock'



- alias: 'Roomba Bin Full'
  trigger:
    - platform: state
      entity_id: binary_sensor.roomba_bin_full
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 0
  action:
    - service: tts.cloud_say
      entity_id:
        - media_player.main_floor
      data:
        message: 'The Roomba bin is full'

