

- id: mb_ac_to_night_setting
  alias: MB AC to night setting
  trigger:
    platform: time_pattern
    hours: 20
    minutes: 00
    seconds: 00
  condition:
    - condition: state
      entity_id: binary_sensor.mb_ac_power
      state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.mb_ac_to_night_setting


- id: mb_ac_to_day_setting
  alias: MB AC to day setting
  trigger:
    platform: time_pattern
    hours: 8
    minutes: 00
    seconds: 00
  condition:
    - condition: state
      entity_id: binary_sensor.mb_ac_power
      state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.mb_ac_to_day_setting

- id: lr_ac_powerful_off
  alias: LR AC Powerful Off
  trigger:
    platform: state
    entity_id: switch.lr_powerful
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 3
  action:
    - service: switch.turn_off
      entity_id: switch.lr_powerful

- id: mb_ac_powerful_off
  alias: MB AC Powerful Off
  trigger:
    platform: state
    entity_id: switch.mb_powerful
    from: "off"
    to: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 3
  action:
    - service: switch.turn_off
      entity_id: switch.mb_powerful


- alias: 'Dryer has stopped'
  trigger:
    - platform: state
      entity_id: sensor.dryer_sensor
      from: 'Running'
      to: 'Cycle Complete'
      for:
        hours: 0
        minutes: 0
        seconds: 0
  action:
    - service: tts.google_translate_say
      entity_id:
        - media_player.dan_speaker
        - media_player.spare_room_speaker
        - media_player.guest_room_speaker
        - media_player.kitchen_speaker
        - media_player.office_home
        - media_player.kelly_home
        - media_player.smart_clock
      data:
        message: >
          {{
            [
              "The dryer has stopped",
              "Better get those clothes out beofre they wrinkle",
              "Dryer! Now!",
              "No more tumbling",
              "The clothing dehydration process has terminated"
            ] | random
          }}


- alias: 'Laundry sink level high'
  trigger:
    platform: state
    entity_id: binary_sensor.high_water
    from: 'off'
    to: 'on'
    for:
      seconds: 5
  condition:
    - condition: state
      entity_id: script.water_warning
      state: 'off'
  action:
  - service: script.turn_on
    entity_id: script.water_warning
  - service: light.turn_on
    entity_id: light.clock_circle
    data:
      effect: 'Police 3'
      brightness: 255
  - service: light.turn_on
    entity_id: light.wall_clock
    data:
      effect: 'Police 3'
      brightness: 255

- alias: 'Laundry sink level back to normal'
  trigger:
    platform: state
    entity_id: binary_sensor.high_water
    from: 'on'
    to: 'off'
    for:
      seconds: 5
  condition:
    - condition: state
      entity_id: script.water_warning
      state: 'on'
  action:
  - service: script.turn_off
    entity_id: script.water_warning
  - service: light.turn_on
    entity_id: light.clock_circle
    data:
      effect: 'Clock'
  - service: light.turn_on
    entity_id: light.wall_clock
    data:
      effect: 'Clock'

- alias: Washer Start

  trigger:
    platform: numeric_state
    entity_id: switch.washer
    value_template: '{{ states.switch.washer.attributes["current_a"] | float }}'
    above: 0.03
    for:
      hours: 0
      minutes: 0
      seconds: 10

  condition:
    - condition: state
      entity_id: input_boolean.washer_status
      state: 'off'

  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.washer_status


- alias: Washer Stop

  trigger:
    platform: numeric_state
    entity_id: switch.washer
    value_template: '{{ states.switch.washer.attributes["current_a"] | float }}'
    below: 0.03
    for:
      hours: 0
      minutes: 2
      seconds: 30

  condition:
    - condition: state
      entity_id: input_boolean.washer_status
      state: 'on'

  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.washer_status

- alias: 'Washer has stopped'
  trigger:
    - platform: state
      entity_id: input_boolean.washer_status
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 0
  action:
    - service: tts.google_translate_say
      entity_id:
        - media_player.dan_speaker
        - media_player.spare_room_speaker
        - media_player.guest_room_speaker
        - media_player.kitchen_speaker
        - media_player.office_home
        - media_player.kelly_home
        - media_player.smart_clock
      data:
        message: >
          {{
            [
              "The washer has stopped",
              "Finally!  That noise was driving me crazy!",
              "Washer! Now!",
              "Better get those clothes into the dryer",
              "Done washing"
            ] | random
          }}


- alias: "Office AC Power Toggle"
  trigger:
    - platform: state
      entity_id: binary_sensor.office_ac_power_button
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.toggle
      data:
        entity_id: input_boolean.office_ac_power


- id: office_ac_eco_toggle
  alias: "Office AC Eco Toggle"
  trigger:
    - platform: state
      entity_id: binary_sensor.office_ac_eco
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.toggle
      data:
        entity_id: input_boolean.office_ac_eco


- id: office_ac_display_toggle
  alias: "Office AC Display Toggle"
  trigger:
    - platform: state
      entity_id: binary_sensor.office_ac_display
      from: 'off'
      to: 'on'
  action:
    - service: input_boolean.toggle
      data:
        entity_id: input_boolean.office_ac_display


- id: office_ac_temp_plus
  alias: "Office AC Temp Plus"
  trigger:
    - platform: state
      entity_id: binary_sensor.office_ac_temp_plus
      from: 'off'
      to: 'on'
  action:
    - service: input_number.increment
      data:
        entity_id: input_number.office_ac_temperature


- id: office_ac_temp_minus
  alias: "Office AC Temp Minus"
  trigger:
    - platform: state
      entity_id: binary_sensor.office_ac_temp_minus
      from: 'off'
      to: 'on'
  action:
    - service: input_number.decrement
      data:
        entity_id: input_number.office_ac_temperature


- id: office_ac_fan_next
  alias: "Office AC Fan Next"
  trigger:
    - platform: state
      entity_id: binary_sensor.office_ac_fan
      from: 'off'
      to: 'on'
  action:
    - service: input_select.select_next
      data:
        entity_id: input_select.office_ac_fan


- id: office_ac_mode_next
  alias: "Office AC Mode Next"
  trigger:
    - platform: state
      entity_id: binary_sensor.office_ac_mode
      from: 'off'
      to: 'on'
  action:
    - service: input_select.select_next
      data:
        entity_id: input_select.office_ac_mode

- id: office_ac_turn_on
  alias: "Office AC On"
  trigger:
    - platform: numeric_state
      entity_id: sensor.office_temperature
      above: 72.9
      for:
        hours: 0
        minutes: 20
        seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.office_ac_power
      state: 'off'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.office_ac_power

- id: office_ac_turn_off
  alias: "Office AC Off"
  trigger:
    - platform: numeric_state
      entity_id: sensor.office_temperature
      below: 70
      for:
        hours: 0
        minutes: 20
        seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.office_ac_power
      state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.office_ac_power



# - alias: 'Roomba Bin Full'
#   trigger:
#     - platform: state
#       entity_id: binary_sensor.roomba_bin_full
#       from: 'off'
#       to: 'on'
#       for:
#         hours: 0
#         minutes: 0
#         seconds: 0
#   action:
#     - service: tts.google_translate_say
#       entity_id:
#         - media_player.dan_speaker
#         - media_player.kitchen_speaker
#         - media_player.office_home
#         - media_player.kelly_home
#         - media_player.smart_clock
#       data:
#         message: 'The Roomba bin is full'

