



- alias: 'Roomba Bin Full'
  trigger:
    - platform: state
      entity_id: binary_sensor.roomba_bin_full
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 0
  action:
    - service: tts.cloud_say
      entity_id:
        - media_player.main_floor
      data:
        message: 'The Roomba bin is full'

