# Outside lights

- id: lights_deck_light_timer
  alias: 'Deck Light Timer'
  trigger:
    - platform: state
      entity_id: switch.deck_light
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 15
        seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.lights_off_automations
    state: "on"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.deck_light

- id: lights_deck_turns_on_woodpile
  alias: 'Deck Light turns on Woodpile Lights'
  trigger:
    - platform: state
      entity_id: switch.deck_light
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 0
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.woodpile_lights

- id: lights_deck_turns_off_woodpile
  alias: 'Deck Light turns off Woodpile Lights'
  trigger:
    - platform: state
      entity_id: switch.deck_light
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 0
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.woodpile_lights

- id: lights_woodpile_lights_timer
  alias: 'Woodpile Lights Timer'
  trigger:
    - platform: state
      entity_id: switch.woodpile_lights
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 10
        seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.lights_off_automations
    state: "on"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.woodpile_lights

- id: lights_path_light_timer
  alias: 'Path Light Timer'
  trigger:
    - platform: state
      entity_id: switch.shelly1l_f4cfa2e397de
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 30
        seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.lights_off_automations
    state: "on"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.shelly1l_f4cfa2e397de


- id: lights_porch_sunset_transition
  alias: Sunset Transition
  trigger:
  - platform: time_pattern
    minutes: '/2'
    seconds: 00
  condition:
    condition: and
    conditions:
      - condition: time
        after: '16:00:00'         #    (the time when a sunset could start in a year)
        before: '23:00:00'        #  (the time when a sunset could end in a year)
      - condition: numeric_state
        entity_id: sensor.sun_elevation
        above: -8
        below: 0
      - condition: or
        conditions:
          - condition: template
            value_template: '{{states.light.front_porch_light.attributes.brightness < ((0.0625*((states.sun.sun.attributes.elevation+8)**2))-(31.125*(states.sun.sun.attributes.elevation+8))+255)|int(1)}}'
          - condition: template
            value_template: '{{ states.light.front_porch_light.attributes.brightness==null }} '
  action:
    - service: light.turn_on
      entity_id: light.front_porch_light
      data_template:
        profile: sunset
        brightness: '{{((0.0625*((states.sun.sun.attributes.elevation+8)**2))-(31.125*(states.sun.sun.attributes.elevation+8))+255)|int(1)}}'

- id: lights_porch_off_midnight
  alias: Turn off front porch light at midnight
  trigger:
    - platform: time_pattern
      hours: 00
      minutes: 00
      seconds: 00
  condition:
    condition: state
    entity_id: input_boolean.lights_off_automations
    state: "on"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.front_porch_light

# Kitchen lights

- id: lights_kitchen_turns_off_sink
  alias: 'Sink Off When Kitch Off'
  trigger:
    - platform: state
      entity_id: switch.kitchen_light
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 0
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.sink_light

- id: lights_undercabinet_morning
  alias: Undercabinet Morning
  trigger:
    - platform: time_pattern
      hours: 06
      minutes: 00
      seconds: 00
  action:
    # - service: light.turn_on
    #   entity_id: light.shellyrgbw2_1dfb87
    #   data:
    #     effect: none
    - service: script.undercabinet_morning

- id: lights_undercabinet_evening
  alias: Undercabinet Evening
  trigger:
    - platform: time_pattern
      hours: 20
      minutes: 00
      seconds: 00
  action:
    # - service: light.turn_on
    #   entity_id: light.shellyrgbw2_1dfb87
    #   data:
    #     effect: none
    - service: script.undercabinet_evening

- id: lights_undercabinet_button
  alias: Undercabinet Button
  trigger:
    - platform: state
      entity_id: binary_sensor.undercabinet_button_push
      from: 'off'
      to: 'on'
  action:
    - service: script.undercabinet_button

# Motion sensor lights

- alias: Turn on laundry light when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.laundry_motion
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.laundry_light

- alias: Turn off laundry light 2 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.laundry_motion
    to: 'off'
    for:
      minutes: 2
  action:
    service: homeassistant.turn_off
    entity_id: switch.laundry_light

- alias: tv_backight_on
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: light.turn_on
      entity_id: light.tv_backlight
      data:
        effect: rainbow
        brightness: 110
        transition: 5

- alias: Basement stair motion light on
  trigger:
    - platform: state
      entity_id: group.basement_stair_motion
      to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.basement_stair

- alias: Basement stair no motion light off
  trigger:
    - platform: state
      entity_id: group.basement_stair_motion
      to: 'off'
      for:
        minutes: 5
  action:
    service: homeassistant.turn_off
    entity_id: light.basement_stair

#---------------------------------------------------------------

- alias: tv_backight_on
  trigger:
    - platform: sun
      event: sunset
  action:
    - service: light.turn_on
      entity_id: light.tv_backlight
      data:
        effect: rainbow
        brightness: 110
        transition: 5

# Living Room

- alias: tv_backlight_off
  trigger:
    - platform: time_pattern
      hours: 00
      minutes: 01
      seconds: 00
  condition:
    condition: state
    entity_id: input_boolean.lights_off_automations
    state: "on"
  action:
    - service: light.turn_off
      entity_id: light.tv_backlight

# Others


- alias: 'Lights off when we all leave'
  trigger:
    platform: state
    entity_id: group.all_persons
    from: 'home'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
    condition: state
    entity_id: input_boolean.lights_off_automations
    state: "on"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.lights
    - service: light.turn_on
      data:
        entity_id: light.kelly_lamp

- alias: 'Upstairs Hall on at sunset'
  trigger:
    - platform: time_pattern
      minutes: '/2'
      seconds: 00
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.shellydimmer2_e8db84d6142e
        state: 'off'
      - condition: state
        entity_id: sensor.sun_state
        state: 'down'
  action:
    - service: homeassistant.turn_on
      entity_id: light.shellydimmer2_e8db84d6142e
      data:
        transition: 3
        brightness: 51

- alias: Turn off upstairs hall light at sunrise
  trigger:
    - platform: state
      entity_id: sensor.sun_state
      from: 'down'
      to: 'up'
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: light.shellydimmer2_e8db84d6142e
        value_template: '{% if states.light.shellydimmer2_e8db84d6142e.state == "on"  %}{{ states.light.shellydimmer2_e8db84d6142e.attributes.brightness }}{% else %}0{% endif %}'
        below: 52
        above: 50
      - condition: state
        entity_id: input_boolean.lights_off_automations
        state: "on"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.shellydimmer2_e8db84d6142e

- alias: 'Light LED Mirror on at sunset'
  trigger:
    - platform: state
      entity_id: sensor.sun_state
      from: 'up'
      to: 'down'
  condition:
    - condition: state
      entity_id: light.led_mirror
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: light.led_mirror
      data:
        effect: Random
        brightness: 198

- alias: 'Light LED Mirror off at sunrise'
  trigger:
    - platform: state
      entity_id: sensor.sun_state
      from: 'down'
      to: 'up'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.led_mirror
        state: 'on'
      - condition: state
        entity_id: input_boolean.lights_off_automations
        state: "on"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.led_mirror

- alias: Tag 1 Scanned
  trigger:
    - platform: tag
      tag_id: bbba54bf-8959-45e1-b39a-54c20343f266
  condition: []
  action:
    - service: script.watch_tv
      data: {}