# Aventon Battery charging

homeassistant:
  customize:
    switch.outdoor_plug_1:
      friendly_name: Aventon Charger
      icon: mdi:bicycle-electric
    input_number.aventon_charge_time:
      icon: mdi:bicycle-electric
    timer.aventon_charger:
      friendly_name: Aventon Charger

input_boolean:
  aventon_charging:
    name: Aventon Battery Charging
    icon: mdi:bicycle-electric

input_number:
  aventon_charge_time:
    name: Aventon Charge Time
    icon: mdi:bicycle-electric
    min: 1
    max: 5
    initial: 3
    mode: box
    unit_of_measurement: hrs

timer:
  aventon_charger:
    duration: "03:00:00"
    icon: mdi:timer-outline
    restore: true

#-----------------------------------------------------------------------------#


automation:
  - alias: Aventon Charge Started
    trigger:
      platform: state
      entity_id: switch.outdoor_plug_1
      to: 'on'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.aventon_charging
      - service: timer.start
        data:
          entity_id: timer.aventon_charger
          duration: "{{ states('input_number.aventon_charge_time') | int(3) * 60 * 60 }}" # time in seconds

  - alias: Aventon Charge Stopped
    trigger:
      platform: state
      entity_id: switch.outdoor_plug_1
      to: 'off'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.aventon_charging
      - service: timer.cancel
        data:
          entity_id: timer.aventon_charger

  - alias: Aventon Charge Complete
    trigger:
      - platform: event
        event_type: timer_finished
        event_data:
            entity_id: timer.aventon_charger
    action:
      - service: switch.turn_off
        entity_id: switch.outdoor_plug_1
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.aventon_charging
