homeassistant:
    customize:
      binary_sensor.dishwasher_door_contact:
        friendly_name: Dishwasher Door
        icon: mdi:dishwasher
      binary_sensor.dishwasher_state:
        icon: mdi:dishwasher
      sensor.dishwasher_status:
        friendly_name: Dishwasher Status
        icon: mdi:dishwasher

binary_sensor:

  - platform: template
    sensors:
      dishwasher_state:
        friendly_name: "Dishwasher State"
        device_class: running
        value_template: >-
          {% if is_state('input_select.dishwasher_status', 'Washing')   %}
            on
          {% else %}
            off
          {% endif %}

input_select:
  dishwasher_status:
    name: Dishwasher Status
    options:
      - Dirty
      - Washing
      - Drying
      - Clean

sensor:

  - platform: template
    sensors:
      dishwasher_status:
        value_template: >-
          {{ states('input_select.dishwasher_status') }}

# automation:

#   - alias: Washer Start

#     trigger:
#       platform: numeric_state
#       entity_id: sensor.washer_current
#       above: 0.03
#       for:
#         hours: 0
#         minutes: 0
#         seconds: 10

#     condition:
#       - condition: state
#         entity_id: input_boolean.washer_status
#         state: 'off'

#     action:
#       - service: input_boolean.turn_on
#         data:
#           entity_id: input_boolean.washer_status


#   - alias: Washer Stop

#     trigger:
#       platform: numeric_state
#       entity_id: sensor.washer_current
#       below: 0.03
#       for:
#         hours: 0
#         minutes: 2
#         seconds: 30

#     condition:
#       - condition: state
#         entity_id: input_boolean.washer_status
#         state: 'on'

#     action:
#       - service: input_boolean.turn_off
#         data:
#           entity_id: input_boolean.washer_status

#   - alias: 'Washer has stopped'
#     trigger:
#       - platform: state
#         entity_id: input_boolean.washer_status
#         from: 'on'
#         to: 'off'
#         for:
#           hours: 0
#           minutes: 0
#           seconds: 0
#     condition:
#       condition: state
#       entity_id: input_boolean.tts_automations
#       state: "on"
#     action:
#       - service: notify.no_bedrooms_cloud
#         data:
#           message: >
#             {{
#               [
#                 "The washer has stopped",
#                 "Better get those clothes into the dryer",
#                 "Done washing"
#               ] | random
#             }}

