homeassistant:
    customize:
      binary_sensor.dishwasher_door_contact:
        friendly_name: Dishwasher Door
        icon: mdi:dishwasher
      sensor.dishwasher_door_battery:
        friendly_name: Dishwasher Door Battery
      sensor.dishwasher_door_temperature:
        friendly_name: Dishwasher Door Temperature
      sensor.dishwasher_door_voltage:
        friendly_name: Dishwasher Door Voltage
      sensor.dishwasher_door_linkquality:
        friendly_name: Dishwasher Door Link Quality
      binary_sensor.dishwasher_state:
        icon: mdi:dishwasher
      sensor.dishwasher_status:
        friendly_name: Dishwasher Status
        icon: mdi:dishwasher
      binary_sensor.dishwasher_switch_cloud:
        friendly_name: Dishwasher Switch Cloud
      binary_sensor.dishwasher_switch_firmware_update:
        friendly_name: Dishwasher Switch Firmware Update
      button.dishwasher_switch_ota_update:
        friendly_name: Dishwasher Switch OTA Update
      button.dishwasher_switch_reboot:
        friendly_name: Dishwasher Switch Reboot
      sensor.dishwasher_switch_rssi:
        friendly_name: Dishwasher Switch WiFi Signal
      switch.dishwasher_switch_switch_0:
        friendly_name: Dishwasher Switch
        icon: mdi:dishwasher
      sensor.dishwasher_switch_switch_0_energy:
        friendly_name: Dishwasher Switch Energy
      binary_sensor.dishwasher_switch_switch_0_input:
        friendly_name: Dishwasher Switch Input
        icon: mdi:light-switch
      binary_sensor.dishwasher_switch_switch_0_overheating:
        friendly_name: Dishwasher Switch Overheating
      binary_sensor.dishwasher_switch_switch_0_overpowering:
        friendly_name: Dishwasher Switch Overpowering
      binary_sensor.dishwasher_switch_switch_0_overvoltage:
        friendly_name: Dishwasher Switch Overvoltage
      sensor.dishwasher_switch_switch_0_power:
        friendly_name: Dishwasher Switch Power
      sensor.dishwasher_switch_switch_0_temperature:
        friendly_name: Dishwasher Switch Temperature
      sensor.dishwasher_switch_switch_0_voltage:
        friendly_name: Dishwasher Switch Voltage
      sensor.dishwasher_switch_uptime:
        friendly_name: Dishwasher Switch Uptime
      input_boolean.dishwasher_empty_reported:
        friendly_name: Dishwasher Empty Reported

binary_sensor:

  - platform: template
    sensors:
      dishwasher_state:
        friendly_name: "Dishwasher State"
        device_class: running
        value_template: >-
          {% if is_state('input_select.dishwasher_status', 'Washing')   %}
            on
          {% else %}
            off
          {% endif %}

input_boolean:
  dishwasher_empty_reported:

input_number:
  dishwasher_start_time:
    name: Dishwasher Start Time
    min: 0
    max: 9999999999
    unit_of_measurement: 's'

input_select:
  dishwasher_status:
    name: Dishwasher Status
    options:
      - Dirty
      - Washing
      - Drying
      - Clean
      - Empty

sensor:

  - platform: template
    sensors:
      dishwasher_status:
        value_template: >-
          {{ states('input_select.dishwasher_status') }}

automation:

  - alias: Dishwasher Start from Dirty or Empty

    trigger:
      platform: numeric_state
      entity_id: sensor.dishwasher_switch_switch_0_power
      above: 1.2
      for:
        hours: 0
        minutes: 0
        seconds: 5

    condition:
      condition: and
      conditions:
        - condition: or
          conditions:
            - condition: state
              entity_id: input_select.dishwasher_status
              state: 'Dirty'
            - condition: state
              entity_id: input_select.dishwasher_status
              state: 'Empty'
        - condition: state
          entity_id: binary_sensor.dishwasher_door_contact
          state: "off"

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Washing
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.dishwasher_empty_reported
      - service: input_number.set_value
        target:
          entity_id: input_number.dishwasher_start_time
        data:
          value: "{{ as_timestamp(now())|round(0) }}"

  - alias: Dishwasher Wash Cycle Complete

    trigger:
      platform: numeric_state
      entity_id: sensor.dishwasher_switch_switch_0_power
      below: 1.0
      for:
        hours: 0
        minutes: 0
        seconds: 30

    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: 'Washing'
      - condition: state
        entity_id: binary_sensor.dishwasher_door_contact
        state: "off"
      - condition: template
        alias: "Duration longer than 21 minutes"
        value_template: "{{ as_timestamp(now())|round(0) - states('input_number.dishwasher_start_time')|int(0) > 1260 }}"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Drying

  - alias: Dishwasher Rinse Cycle Complete

    trigger:
      platform: numeric_state
      entity_id: sensor.dishwasher_switch_switch_0_power
      below: 1.0
      for:
        hours: 0
        minutes: 0
        seconds: 30

    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: 'Washing'
      - condition: state
        entity_id: binary_sensor.dishwasher_door_contact
        state: "off"
      - condition: template
        alias: "Duration shorter than 21 minutes"
        value_template: "{{ as_timestamp(now())|round(0) - states('input_number.dishwasher_start_time')|int(0)  < 1261 }}"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Dirty

  - alias: Dishwasher Dry Cycle Complete

    trigger:
      platform: state
      entity_id: input_select.dishwasher_status
      from: Washing
      to: Drying
      for:
        hours: 0
        minutes: 13
        seconds: 30

    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: 'Drying'
      - condition: state
        entity_id: binary_sensor.dishwasher_door_contact
        state: "off"

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Clean

  - alias: Dishwasher Emptied
  # Door opened while Clean or Drying
    trigger:
      platform: state
      entity_id: binary_sensor.dishwasher_door_contact
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 00

    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.dishwasher_status
          state: 'Clean'
        - condition: state
          entity_id: input_select.dishwasher_status
          state: 'Drying'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Empty

  - alias: Dishwasher Door Opened While Washing

    trigger:
      platform: state
      entity_id: binary_sensor.dishwasher_door_contact
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 1
        seconds: 00

    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: 'Washing'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Dirty

  - alias: Dishwasher Door Opened While Empty

    trigger:
      platform: state
      entity_id: binary_sensor.dishwasher_door_contact
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 10

    condition:
      - condition: state
        entity_id: input_select.dishwasher_status
        state: 'Empty'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dishwasher_status
          option: Dirty

# Announcements

  - alias: Dishwasher Ready to Empty
    trigger:
      - platform: state
        entity_id: input_select.dishwasher_status
        to: 'Clean'
        for:
          hours: 0
          minutes: 0
          seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.tts_automations
        state: "on"
      - condition: state
        entity_id: binary_sensor.dishwasher_door_contact
        state: "off"
    action:
      - service: notify.dan_cloud
        data:
          message: >
            {{
              [
                "The dishwasher is ready to empty",
                "Them there dishes is sparklin clean",
                "Dishes are done"
              ] | random
            }}

  - alias: Dishwasher Has Been Emptied
     # Door closes while empty and not already reported
    trigger:
      platform: state
      entity_id: binary_sensor.dishwasher_door_contact
      from: "on"
      to: "off"
      for:
        hours: 0
        minutes: 0
        seconds: 05
    condition:
      - condition: state
        entity_id: input_boolean.tts_automations
        state: "on"
      - condition: state
        entity_id: input_select.dishwasher_status
        state: 'Empty'
      - condition: state
        entity_id: input_boolean.dishwasher_empty_reported
        state: "off"
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.dishwasher_empty_reported
      - service: notify.kitchen_cloud
        data:
          message: >
            {{
              [
                "The dishwasher has been emptied",
                "No dishes in here!!",
                "Dishes put away"
              ] | random
            }}

# Dishwasher Display

  - alias: Dishwasher Display Off at Midnight
    trigger:
      - platform: time_pattern
        hours: 00
        minutes: 00
        seconds: 00
    condition:
      condition: state
      entity_id: input_boolean.lights_off_automations
      state: "on"
    action:
      - service: switch.turn_off
        data:
          entity_id: switch.dishwasher_display_backlight

  - alias: Dishwasher Display On in the Morning
    trigger:
      - platform: time_pattern
        hours: 05
        minutes: 45
        seconds: 00
    action:
      - service: switch.turn_on
        data:
          entity_id: switch.dishwasher_display_backlight

script:

  # Rollback status
  dishwasher_rollback_status:
    sequence:
      - service: input_select.select_previous
        target:
          entity_id: input_select.dishwasher_status

