homeassistant:
  customize:
    sensor.living_room_tv_status:
      icon: mdi:television
      friendly_name: Living Room TV Status
    sensor.tv_reset_current_voltage:
      friendly_name: Living Room TV Voltage
    sensor.tv_reset_energy_use_monthly:
      friendly_name: Living Room TV Monthly Energy
    sensor.tv_reset_energy_use_weekly:
      friendly_name: Living Room TV Weekly Energy
    sensor.tv_reset_energy_use_yearly:
      friendly_name: Living Room TV Annual Energy

sensor:

  - platform: template
    sensors:
      living_room_tv_status:
        value_template: >-
          {% set tv_power = states('sensor.tv_reset_current_power') | float %}

          {% if tv_power <= 0 %}
             No Power
          {% elif 0 < tv_power < 100 %}
             Standby
          {% elif 100 <= tv_power %}
             On
          {% else %}
             Unknown
          {% endif %}

script:

  lr_tv_channelup:
    sequence:
      - service: rest_command.lr_tv_channelup
  lr_tv_channeldown:
    sequence:
      - service: rest_command.lr_tv_channeldown
  lr_tv_last:
    sequence:
      - service: rest_command.lr_tv_last
  lr_tv_home:
    sequence:
      - service: rest_command.lr_tv_home
  lr_tv_info:
    sequence:
      - service: rest_command.lr_tv_info
  lr_tv_cablebox:
    sequence:
      - service: rest_command.lr_tv_cablebox
  lr_tv_louder:
    sequence:
      - service: rest_command.lr_tv_louder
  lr_tv_muchlouder:
    sequence:
      - service: rest_command.lr_tv_muchlouder
  lr_tv_softer:
    sequence:
      - service: rest_command.lr_tv_softer
  lr_tv_muchsofter:
    sequence:
      - service: rest_command.lr_tv_muchsofter
  lr_tv_tcm:
    sequence:
      - service: rest_command.lr_tv_tcm

rest_command:
  lr_tv_channelup:
    url: "http://192.168.254.31/channelup"
  lr_tv_channeldown:
    url: "http://192.168.254.31/channeldown"
  lr_tv_last:
    url: "http://192.168.254.31/last"
  lr_tv_home:
    url: "http://192.168.254.31/home"
  lr_tv_cablebox:
    url: "http://192.168.254.31/cablebox"
  lr_tv_info:
    url: "http://192.168.254.31/info"
  lr_tv_louder:
    url: "http://192.168.254.31/louder"
  lr_tv_muchlouder:
    url: "http://192.168.254.31/muchlouder"
  lr_tv_muchsofter:
    url: "http://192.168.254.31/muchsofter"
  lr_tv_softer:
    url: "http://192.168.254.31/softer"
  lr_tv_tcm:
    url: "http://192.168.254.31/811"

cloud:
  google_actions:
    filter:
      include_entities:
        - button.living_room_ir_tv_all_on_off
        - button.living_room_ir_sony_tv_mute
        - button.living_room_ir_cnn
        - button.living_room_ir_science_channel

    entity_config:

      button.living_room_ir_tv_all_on_off:
        name: Living Room TV On
        aliases:
          - LR TV On
          - turn on living room tv
          - turn off living room tv
          - LR tv off
          - Living room tv off
        room: Living Room

      button.living_room_ir_sony_tv_mute:
        name: Living Room mute
        aliases:
          - LR TV mute
          - mute living room tv
          - mute tv
          - mute the tv
        room: Living Room

      button.living_room_ir_cnn:
        name: CNN
        aliases:
          - activate CNN
          - push CNN
          - switch to science
        room: Living Room

      button.living_room_ir_science_channel:
        name: Science
        aliases:
          - activate Science
          - push science
          - switch to SCIENCE
        room: Living Room