homeassistant:
  customize:
    binary_sensor.bed_sensor_mat:
      device_class: occupancy
    binary_sensor.bed_sensor_mat_icon:
      friendly_name: "Master Bed Occupancy"



binary_sensor:
  - platform: template
    sensors:
      bed_sensor_mat_icon:
        value_template: >-
          {% if is_state('binary_sensor.bed_sensor_mat', 'on')   %}
            on
          {% else %}
            off
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.bed_sensor_mat', 'on') %}
            mdi:bed
          {% else %}
            mdi:bed-empty
          {% endif %}
        device_class: occupancy

automation:

  - alias: 'Master Bed Get Up - Hall Light On'
    trigger:
      - platform: state
        entity_id: binary_sensor.bed_sensor_mat
        from: 'on'
        to: 'off'
        for:
          hours: 0
          minutes: 0
          seconds: 1
    condition:
      condition: and
      conditions:
        - condition: time
          after: '21:30:00'
          before: '08:00:00'
        - condition: state
          entity_id: light.shellydimmer2_e8db84d6142e
          state: 'off'
        - condition: state
          entity_id: sensor.sun_state
          state: 'down'
    action:
      - service: light.turn_on
        entity_id: light.shellydimmer2_e8db84d6142e
        data:
          brightness: 51
          transition: 1

  - alias: 'Master Bed Lie Down - Closet Off'
    trigger:
      - platform: state
        entity_id: binary_sensor.bed_sensor_mat
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 0
          seconds: 1
    condition:
      condition: and
      conditions:
        - condition: time
          after: '21:30:00'
          before: '08:00:00'
        - condition: state
          entity_id: light.master_closet
          state: 'on'
        - condition: state
          entity_id: input_boolean.lights_off_automations
          state: "on"
    action:
      - service: light.turn_off
        entity_id: light.master_closet
        data:
          transition: 5

  - alias: 'Master Bed Lie Down - Room Lights Off'
    trigger:
      - platform: state
        entity_id: binary_sensor.bed_sensor_mat
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 0
          seconds: 30
    condition:
      condition: and
      conditions:
        - condition: time
          after: '21:00:00'
          before: '08:00:00'
        - condition: state
          entity_id: input_boolean.lights_off_automations
          state: "on"
    action:
      - service: light.turn_off
        data:
          entity_id: light.master_bedroom
          transition: 10

  - alias: 'Master Bed Get Up - Stairway'
    trigger:
      - platform: state
        entity_id: binary_sensor.bed_sensor_mat
        from: 'on'
        to: 'off'
        for:
          hours: 0
          minutes: 0
          seconds: 1
    condition:
      condition: and
      conditions:
        - condition: time
          after: '05:30:00'
          before: '08:30:00'
        - condition: state
          entity_id: light.stairway_light
          state: 'off'
        - condition: state
          entity_id: sensor.sun_state
          state: 'down'
    action:
      - service: light.turn_on
        entity_id: light.stairway_light
        data:
          transition: 3
          brightness: 13

  - alias: 'Morning Clean Up - Stairway Light'
    trigger:
      - platform: state
        entity_id: sensor.sun_state
        from: 'down'
        to: 'up'
        for:
          hours: 0
          minutes: 30
          seconds: 3
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: light.stairway_light
          value_template: '{% if is_state("light.stairway_light", "on")  %}{{ state_attr("light.stairway_light", "brightness") }}{% else %}0{% endif %}'
          below: 14
          above: 12
        - condition: state
          entity_id: input_boolean.lights_off_automations
          state: "on"
    action:
      - service: light.turn_off
        entity_id: light.stairway_light
        data:
          transition: 1


  - id: phone_charging_stops
    alias: Phone Stops Charging
    trigger:
      platform: state
      entity_id: sensor.sm_g975u_charger_type
      from: wireless
      to: none
      for:
        hours: 0
        minutes: 10
        seconds: 10
    condition:
      condition: and
      conditions:
        - condition: time
          after: '06:00:00'
          before: '09:00:00'
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: "on"
        - condition: state
          entity_id: device_tracker.sm_g975u
          state: "home"
        - condition: state
          entity_id: binary_sensor.mb_ac_power
          state: 'on'
        - condition: state
          entity_id: binary_sensor.bed_sensor_mat
          state: 'off'
        - condition: template
          value_template: "{{ state_attr('climate.master_bedroom_ac','temperature')< 66 }}"
        - condition: state
          entity_id: input_boolean.ac_automations
          state: "on"
    action:
      - service: script.turn_on
        data:
          entity_id: script.mb_ac_to_day_setting
      - service: light.turn_on
        entity_id: light.shellydimmer2_e8db84d6142e
        data:
          brightness: 128

  - id: phone_charging_stops_weekend
    alias: Phone Stops Charging on Weekend
    trigger:
      platform: state
      entity_id: sensor.sm_g975u_charger_type
      from: wireless
      to: none
      for:
        hours: 0
        minutes: 10
        seconds: 10
    condition:
      condition: and
      conditions:
        - condition: time
          after: '06:00:00'
          before: '10:30:00'
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: "off"
        - condition: state
          entity_id: device_tracker.sm_g975u
          state: "home"
        - condition: state
          entity_id: binary_sensor.mb_ac_power
          state: 'on'
        - condition: state
          entity_id: binary_sensor.bed_sensor_mat
          state: 'off'
        - condition: template
          value_template: "{{ state_attr('climate.master_bedroom_ac','temperature')< 66 }}"
        - condition: state
          entity_id: input_boolean.ac_automations
          state: "on"
    action:
      - service: script.turn_on
        data:
          entity_id: script.mb_ac_to_day_setting

  - id: phone_charging_starts
    alias: Phone Starts Charging
    trigger:
      platform: state
      entity_id: sensor.sm_g975u_charger_type
      from: none
      to: wireless
      for:
        hours: 0
        minutes: 0
        seconds: 20
    condition:
      condition: and
      conditions:
        - condition: time
          after: '21:00:00'
          before: '23:59:59'
        - condition: state
          entity_id: device_tracker.sm_g975u
          state: "home"
        - condition: state
          entity_id: binary_sensor.mb_ac_power
          state: 'on'
        - condition: template
          value_template: "{{ state_attr('climate.master_bedroom_ac','temperature') > 65 }}"
        - condition: state
          entity_id: input_boolean.ac_automations
          state: "on"
    action:
      - service: script.turn_on
        data:
          entity_id: script.mb_ac_to_night_setting