homeassistant:
  customize:
    sensor.dressers_brightness:
      icon: mdi:alarm-light-outline
    light.master_bedroom:
      friendly_name: Master Bedroom Lights
    sensor.master_closet_motion_battery:
      friendly_name: Master Closet Motion Battery
    binary_sensor.master_closet_motion_battery_low:
      friendly_name: Master Closet Motion Low Battery
    binary_sensor.master_closet_motion_occupancy:
      friendly_name: Master Closet Motion
    binary_sensor.master_closet_motion_tamper:
      friendly_name: Master Closet Motion Tamper
    sensor.master_closet_motion_linkquality:
      friendly_name: Master Closet Motion Link Quality
    sensor.master_dimmer_brightness:
      friendly_name: Master Dimmer Brightness
      icon: mdi:brightness-7
    sensor.master_bedroom_brightness:
      friendly_name: "Master Brightness"
      icon: mdi:brightness-7
    binary_sensor.mm_wave_1_occupancy:
      friendly_name: "Master Occupancy"
      device_class: Occupancy
      icon: mdi:human


light:

  - platform: group
    name: Dressers
    unique_id: Dresser Lights
    entities:
      - light.dresser_1
      - light.dresser_2

  - platform: group
    name: master_bedroom
    unique_id: Master Bedroom Lights
    entities:
      - light.dan_bedside_lamp
      - light.kelly_bedside_lamp
      - light.dresser_1
      - light.dresser_2
      - light.master_closet

scene:

  # Master Bedroom

  - name: nighttime
    entities:
      light.kelly_bedside_lamp:
        state: on
        brightness: 5
        rgb_color: [0,0,255]   #blue
        effect: colorloop
      light.dan_bedside_lamp:
        state: off
      light.dresser_1:
        state: off
      light.dresser_2:
        state: off

  - name: master_dressers
    entities:
      light.kelly_bedside_lamp:
        state: off
      light.dan_bedside_lamp:
        state: off
      light.dresser_1:
        state: on
        brightness: 5
      light.dresser_2:
        state: on
        brightness: 5

  - name: master_warm
    entities:
      light.kelly_bedside_lamp:
        state: on
        brightness: 191
        color_temp: 450
      light.dan_bedside_lamp:
        state: on
        brightness: 191
        color_temp: 450
      light.dresser_1:
        state: on
        brightness: 191
      light.dresser_2:
        state: on
        brightness: 191

  - name: master_cool
    entities:
      light.kelly_bedside_lamp:
        state: on
        brightness: 204
        color_temp: 203
      light.dan_bedside_lamp:
        state: on
        brightness: 204
        color_temp: 203
      light.dresser_1:
        state: off
      light.dresser_2:
        state: off

  - name: master_bright
    entities:
      light.kelly_bedside_lamp:
        state: on
        brightness: 255
        color_temp: 329
      light.dan_bedside_lamp:
        state: on
        brightness: 255
        color_temp: 329
      light.dresser_1:
        state: on
        brightness: 255
      light.dresser_2:
        state: on
        brightness: 255

  - name: master_dim
    entities:
      light.kelly_bedside_lamp:
        state: on
        brightness: 55
        xy_color: [0.4575, 0.4099]
      light.dan_bedside_lamp:
        state: on
        brightness: 55
        xy_color: [0.4575, 0.4099]
      light.dresser_1:
        state: on
        brightness: 55
      light.dresser_2:
        state: on
        brightness: 55

  - name: master_blue
    entities:
      light.kelly_bedside_lamp:
        state: on
        brightness: 255
        rgb_color: [0,0,255]   #blue
      light.dan_bedside_lamp:
        state: on
        brightness: 255
        rgb_color: [0,0,255]   #blue
      light.dresser_1:
        state: off
      light.dresser_2:
        state: off

  - name: master_off
    entities:
      light.kelly_bedside_lamp:
        state: off
      light.dan_bedside_lamp:
        state: off
      light.master_closet:
        state: off
      light.dresser_1:
        state: off
      light.dresser_2:
        state: off

sensor:
  - platform: template
    sensors:
      dressers_brightness:
        friendly_name: "Dressers Brightness"
        value_template: "{{ state_attr('light.dressers', 'brightness') | int(0) }}"

template:
  sensor:
    - name: master_bedroom_brightness
      state: "{{ state_attr('light.master_bedroom', 'brightness') | int(0) }}"

mqtt:
  sensor:
    - name: master_dimmer_brightness
      state_topic: "zigbee2mqtt/Master Dimmer"
      value_template: "{{ value_json.brightness }}"

input_select:
  master_light_status:
    name: Master Light Status
    options:
      - Dressers
      - Dim
      - Bright
      - Blue

script:
  master_lights_time_based_on:
    alias: Master Lights Time Based On
    sequence:
      - choose:
          - conditions:
            - condition: time
              after: "05:59:59"
              before: "07:30:00"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.master_dim
              - service: input_select.select_option
                data:
                  entity_id: input_select.master_light_status
                  option: Dim
          - conditions:
            - condition: time
              after: "07:29:59"
              before: "21:30:01"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.master_bright
              - service: input_select.select_option
                data:
                  entity_id: input_select.master_light_status
                  option: Bright
          - conditions:
            - condition: time
              after: "21:30:00"
              before: "06:00:00"
            - condition: state    ## and bed occupied
              entity_id: binary_sensor.bed_sensor_mat
              state: "on"
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.master_dressers
              - service: input_select.select_option
                data:
                  entity_id: input_select.master_light_status
                  option: Dressers
          - conditions:
            - condition: time
              after: "21:30:00"
              before: "06:00:00"
              ## and bed not occupied
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.master_blue
              - service: input_select.select_option
                data:
                  entity_id: input_select.master_light_status
                  option: Blue

  master_around_the_horn:
    alias: Master Around the Horn
    sequence:
      - alias: looping_time
        repeat:
          while:
            - condition: state
              entity_id: binary_sensor.bed_sensor_mat
              state: "on"
            # - condition: template
            #   value_template: "{{ repeat.index <= 20 }}"
          sequence:
            - service: script.master_around_the_horn_loop
      - service: script.turn_on
        data:
          entity_id: script.master_lights_time_based_on

  master_around_the_horn_loop:
    sequence:
      - service: scene.turn_on
        data:
          entity_id: scene.master_off
      - service: light.turn_on
        data:
          entity_id: light.dan_bedside_lamp
          brightness: 255
          transition: 0
      - delay:
          milliseconds: 250
      - service: light.turn_off
        data:
          entity_id: light.dan_bedside_lamp
          transition: 0
      - service: light.turn_on
        data:
          entity_id: light.kelly_bedside_lamp
          brightness: 255
          transition: 0
      - delay:
          milliseconds: 250
      - service: light.turn_off
        data:
          entity_id: light.kelly_bedside_lamp
          transition: 0
      - service: light.turn_on
        data:
          entity_id: light.dresser_1
          brightness: 255
          transition: 0
      - delay:
          milliseconds: 250
      - service: light.turn_off
        data:
          entity_id: light.dresser_1
          transition: 0
      - service: light.turn_on
        data:
          entity_id: light.dresser_2
          brightness: 255
          transition: 0
      - delay:
          milliseconds: 250
      - service: light.turn_off
        data:
          entity_id: light.dresser_2
          transition: 0

automation:
  - id: master_lights_sunrise
    alias: Master Lights Sunrise
    trigger:
      - platform: time_pattern
        hours: 6
        minutes: '/1'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '06:29:59'
          before: '06:59:59'
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: "on"
    action:
      - service: light.turn_on
        entity_id: light.dressers
        data_template:
          brightness: '{{ ((now().minute - 30) * 255/58 ) | int(255) }}'

  - id: master_lights_wakeup
    alias: Master Lights Wakeup
    trigger:
      - platform: time_pattern
        hours: 07
        minutes: 00
        seconds: 01
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.master_closet
          state: "off"
        ## Check is bed if occupied
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: "on"
    action:
      - service: light.turn_on
        entity_id: light.master_bedroom
        data_template:
          brightness: 255
          rgb_color: [255,255,255]

  - id: master_lights_wakeup_now
    alias: Master Lights Wakeup Now
    trigger:
      - platform: time_pattern
        hours: 07
        minutes: 30
        seconds: 01
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: light.master_closet
          state: "off"
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: "on"
    action:
      - service: script.master_around_the_horn

  - id: master_lights_give_up
    alias: Master Lights Give Up
    trigger:
      - platform: time_pattern
        hours: 08
        minutes: 00
        seconds: 01
    condition:
      - condition: state
        entity_id: script.master_around_the_horn
        state: 'on'
    action:
      - service: script.turn_off
        entity_id: script.master_around_the_horn


  - id: master_lights_morning_cleanup
    alias: Master Lights Morning Cleanup
    trigger:
      - platform: time_pattern
        hours: 08
        minutes: 00
        seconds: 00
    condition:
      condition: state
      entity_id: input_boolean.lights_off_automations
      state: "on"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: light.dressers

#-------------------------------------------------------------------------#

  - id: master_closet_movement
    alias: Master Closet Movement
    trigger:
      platform: state
      entity_id: binary_sensor.master_closet_motion_occupancy
      to: 'on'
    action:
      service: light.turn_on
      data:
        entity_id: light.master_closet
        brightness: 255

  - id: master_closet_motion_timer
    alias: 'Master Closet Motion Timer'
    trigger:
      platform: state
      entity_id: binary_sensor.master_closet_motion_occupancy
      to: 'off'
      for:
        minutes: 2
    action:
      service: light.turn_off
      entity_id: light.master_closet

  - id: master_closet_light_timer
    alias: 'Master Closet Light Timer'
    trigger:
      - platform: state
        entity_id: light.master_closet
        from: 'off'
        to: 'on'
        for:
          hours: 0
          minutes: 15
          seconds: 0
    condition:
      condition: state
      entity_id: input_boolean.lights_off_automations
      state: "on"
    action:
      - service: light.turn_off
        data:
          entity_id: light.master_closet

#-------------------------------------------------------------------------#

  - id: master_dimmer_on_press
    alias: 'Master Dimmer On Press When Off'
    trigger:
    - trigger: state
      entity_id: event.shelly_blu_button1_a287_button_1
      attribute: event_type
      to: "press"
    condition:
      condition: state
      entity_id: light.master_bedroom
      state: "off"
    action:
      - service: script.turn_off
        entity_id: script.master_around_the_horn
      - service: script.turn_on
        data:
          entity_id: script.master_lights_time_based_on

  - id: master_dimmer_on_press_when_on
    alias: 'Master Dimmer On Press When On'
    trigger:
    - trigger: state
      entity_id: event.shelly_blu_button1_a287_button_1
      attribute: event_type
      to: "press"
    condition:
      condition: state
      entity_id: light.master_bedroom
      state: "on"
    action:
      - service: script.turn_off
        entity_id: script.master_around_the_horn
      - service: input_select.select_next
        target:
          entity_id: input_select.master_light_status

  - id: master_dimmer_on_hold
    alias: 'Master Dimmer On Hold'
    trigger:
    - trigger: state
      entity_id: event.shelly_blu_button1_a287_button_1
      attribute: event_type
      to: 'hold_press'
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.master_bright
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_status
          option: Bright

  - id: master_dimmer_off_hold
    alias: 'Master Dimmer Off Hold'
    trigger:
    - trigger: state
      entity_id: event.shelly_blu_button1_a287_button_4
      attribute: event_type
      to: 'hold_press'
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.master_dressers
      - service: input_select.select_option
        data:
          entity_id: input_select.master_light_status
          option: Dressers

  - id: master_dimmer_off_press
    alias: 'Master Dimmer Off Press'
    trigger:
    - trigger: state
      entity_id: event.shelly_blu_button1_a287_button_4
      attribute: event_type
      to: 'press'
    action:
      - service: script.turn_off
        entity_id: script.master_around_the_horn
      - service: light.turn_off
        data:
          entity_id: light.master_bedroom

  - id: master_dimmer_up_down_press
    alias: 'Master Dimmer Up Down Press'
    mode: queued
    trigger:
      - platform: state
        entity_id: sensor.master_dimmer_action
        to: 'up_press'
      - platform: state
        entity_id: sensor.master_dimmer_action
        to: 'down_press'
      - platform: state
        entity_id: sensor.master_dimmer_action
        to: 'up_hold'
      - platform: state
        entity_id: sensor.master_dimmer_action
        to: 'down_hold'
      - platform: state
        entity_id: sensor.master_dimmer_action
        to: 'up_hold_release'
      - platform: state
        entity_id: sensor.master_dimmer_action
        to: 'down_hold_release'
    action:
      - service: light.turn_on
        data:
          entity_id: light.master_bedroom
          brightness: "{{ states('sensor.master_dimmer_brightness') }}"

  - id: master_dimmer_set_scene
    alias: Master Dimmer Set Scene
    trigger:
      - platform: state
        entity_id: input_select.master_light_status
    action:
      - choose:
          - conditions:
            - condition: state
              entity_id: input_select.master_light_status
              state: 'Dressers'
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.master_dressers
          - conditions:
            - condition: state
              entity_id: input_select.master_light_status
              state: 'Dim'
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.master_dim
          - conditions:
            - condition: state
              entity_id: input_select.master_light_status
              state: 'Bright'
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.master_bright
          - conditions:
            - condition: state
              entity_id: input_select.master_light_status
              state: 'Blue'
            sequence:
              - service: scene.turn_on
                target:
                  entity_id: scene.master_blue

#-------------------------------------------------------------------------#

## Turn on/off lights only when bed is unoccupied

  - id: master_room_occupied
    alias: Master Room Occupied
    trigger:
      platform: state
      entity_id: binary_sensor.mm_wave_1_occupancy
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: time
          after: "06:30:00"
          before: "23:00:00"
        # - condition: state
        #   entity_id: binary_sensor.bed_sensor_mat
        #   state: "off"
        - condition: state
          entity_id: light.master_bedroom
          state: "off"
    action:
      - service: script.turn_on
        data:
          entity_id: script.master_lights_time_based_on

  - id: master_room_unoccupied
    alias: 'Master Room Unoccupied'
    trigger:
      platform: state
      entity_id: binary_sensor.mm_wave_1_occupancy
      to: 'off'
      for:
        minutes: 10
#    condition:
#        - condition: state
#          entity_id: binary_sensor.bed_sensor_mat
#          state: "off"
    action:
      service: light.turn_off
      entity_id: light.master_bedroom
