homeassistant:
  customize:
    sensor.office_south_shade_linkquality:
      friendly_name: Office South Shade Link Quality
    sensor.office_south_shade_mode:
      friendly_name: Office South Shade Mode
    sensor.office_south_shade_position:
      icon: mdi:blinds
      friendly_name: Office South Shade Position
    sensor.office_south_shade_state:
      icon: mdi:blinds
      friendly_name: Office South Shade State

sensor:

  - platform: template
    sensors:
      office_south_shade_position:
        value_template: "{{ state_attr('cover.office_south_shade', 'current_position') }}"
        unit_of_measurement: '%'

  - platform: template
    sensors:
      office_south_shade_state:
        value_template: "{{ states('cover.office_south_shade') }}"

script:

  office_south_shade_open:
    alias: Office South Shade Open
    sequence:
      - repeat:
          while:
            - condition: state
              entity_id: cover.office_south_shade
              state: "closed"
            - condition: template
              value_template: "{{ repeat.index <= 20 }}"
          sequence:
            - service: cover.open_cover
              target:
                entity_id: cover.office_south_shade
            - delay: 00:00:30

  office_south_shade_close:
    alias: Office South Shade Close
    sequence:
      - service: cover.close_cover
        target:
          entity_id: cover.office_south_shade
      - repeat:
          while:
            - condition: state
              entity_id: cover.office_south_shade
              state: "open"
            - condition: template
              value_template: "{{ repeat.index <= 20 }}"
          sequence:
            - service: cover.close_cover
              target:
                entity_id: cover.office_south_shade
            - delay: 00:00:30

automation:

  ## Close at sunset
  - id: shade_sunset_close
    alias: Office South Shade Sunset Close
    trigger:
      - platform: sun
        event: sunset
    condition:
      condition: state
      entity_id: cover.office_south_shade
      state: "open"
    action:
      - service: script.office_south_shade_close

## Open at 8am or 8:30am on weekdays if sun is up
  - alias: Office South Shade Weekday Open
    id: shade_weekday_open
    trigger:
      - platform: time_pattern
        hours: 08
        minutes: 00
        seconds: 00
      - platform: time_pattern
        hours: 08
        minutes: 30
        seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: cover.office_south_shade
          state: "closed"
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: "on"
        - condition: state
          entity_id: input_boolean.vacation_automations
          state: "off"
        - condition: template
          value_template: "{{ state_attr('sun.sun', 'elevation') > 0 }}"
    action:
      - service: script.office_south_shade_open
      # - delay: 00:00:14
      # - service: cover.stop_cover
      #   target:
      #     entity_id: cover.office_south_shade
      # - service: cover.stop_cover
      #   target:
      #     entity_id: cover.office_south_shade


  ## Open at 10am on weekends
  - alias: Office South Shade Weekend Open
    id: shade_weekend_open
    trigger:
      - platform: time_pattern
        hours: 10
        minutes: 00
        seconds: 00
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: cover.office_south_shade
          state: "closed"
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: "off"
        - condition: state
          entity_id: input_boolean.vacation_automations
          state: "off"
    action:
      - service: script.office_south_shade_open
      # - delay: 00:00:10
      # - service: cover.stop_cover
      #   target:
      #     entity_id: cover.office_south_shade

