# Light, scripts, and automations for a 3-way-switch using a Shelly 2.5.
# This method should be used when the line power comes into the switch box from
# the source, not when it enters the light box first.
homeassistant:
  customize:
    light.ceiling_lights:
      icon: mdi:lightbulb-outline

light:
  # A template light is not tied to any entity in Hass, instead using scripts to 'turn on' or 'turn off'
  - platform: template
    lights:
      ceiling_lights:
        friendly_name: Ceiling Lights
        unique_id: ceiling_lights
        turn_off:
          service: script.ceiling_lights_turn_off
        turn_on:
          service: script.ceiling_lights_turn_on

script:
  # If the power levels are low, that means the physical lights aren't on, so flip the realy to turn on the light
  ceiling_lights_turn_on:
    alias: Ceiling Lights Turn On
    sequence:
      - choose:
        - alias: Power is low
          conditions:
            - condition: and
              conditions:
                - condition: numeric_state
                  entity_id: sensor.shellyswitch25_3c6105e43c53_channel_1_power
                  below: 2
                - condition: numeric_state
                  entity_id: sensor.shellyswitch25_3c6105e43c53_channel_2_power
                  below: 2
          sequence:
            - service: switch.toggle
              entity_id: switch.shellyswitch25_3c6105e43c53_channel_1

  ceiling_lights_turn_off:
  # If the power levels are high, that means the physical lights are on, so flip the realy to turn off the light
    alias: Ceiling Lights Turn Off
    sequence:
      - choose:
        - alias: Power is high
          conditions:
            - condition: or
              conditions:
                - condition: numeric_state
                  entity_id: sensor.shellyswitch25_3c6105e43c53_channel_1_power
                  above: 1.9
                - condition: numeric_state
                  entity_id: sensor.shellyswitch25_3c6105e43c53_channel_2_power
                  above: 1.9
          sequence:
            - service: switch.toggle
              entity_id: switch.shellyswitch25_3c6105e43c53_channel_1

automation:
  # At a power up event, we mark the Hass light as On if it isn't already.
  # Usually means someone flipped the wall switch
  - id: ceiling_lights_power_up
    alias: Ceiling Lights Power Up
    trigger:
      - platform: numeric_state
        entity_id: sensor.shellyswitch25_3c6105e43c53_channel_1_power
        above: 1.9
      - platform: numeric_state
        entity_id: sensor.shellyswitch25_3c6105e43c53_channel_2_power
        above: 1.9
    condition:
      - condition: state
        entity_id: light.ceiling_lights
        state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.ceiling_lights

  # At a power down event, we mark the Hass light as Off if it isn't already.
  # Usually means someone flipped the wall switch
  - id: ceiling_lights_power_down
    alias: Ceiling Lights Power Down
    trigger:
      - platform: numeric_state
        entity_id: sensor.shellyswitch25_3c6105e43c53_channel_1_power
        below: 2
      - platform: numeric_state
        entity_id: sensor.shellyswitch25_3c6105e43c53_channel_2_power
        below: 2
    condition:
      - condition: state
        entity_id: light.ceiling_lights
        state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.ceiling_lights

#  Shelly 2.5 Config
#
#  Channel 1
#    Power On Default Mode - Restore Last Mode
#    Button type - Edge Switch
#
#    Output Switched On URL
#      Enabled - Checked
#      URL     - http://localhost/relay/1?turn=off
#
#    Output Switched Off URL
#      Enabled - Checked
#      URL     - http://localhost/relay/1?turn=on
#
#  Channel 2
#    Button type - Detached switch
#