homeassistant:
  customize:
    sensor.usps_mail:
      friendly_name: USPS Mail
      icon: mdi:email-outline
    sensor.usps_packages:
      icon: mdi:package-variant-closed
      friendly_name: USPS Packages

group:
  USPS:
    entities:
      - sensor.usps_mail
      - sensor.usps_packages
      - camera.usps_mail_pictures

sensor:
  - platform: mqtt
    name: 'USPS Mail'
    state_topic: 'usps/mails'
    value_template: "{{ value }}"

  - platform: mqtt
    name: USPS Packages
    state_topic: 'usps/packages'
    value_template: "{{ value }}"

camera:
  - platform: generic
    name: USPS Mail Pictures
    still_image_url: 'http://192.168.254.118:8123/local/images/todays_mails.gif'
