homeassistant:
    customize:
      binary_sensor.washer_lid_contact:
        friendly_name: Washer Lid
        icon: mdi:washing-machine
      sensor.washer_lid_battery:
        friendly_name: Washer Lid Battery
      sensor.washer_lid_temperature:
        friendly_name: Washer Lid Temperature
      sensor.washer_lid_voltage:
        friendly_name: Washer Lid Voltage
      sensor.washer_lid_linkquality:
        friendly_name: Washer Lid Link Quality
      switch.washer:
        icon: mdi:light-switch
        friendly_name: Washer Switch
      sensor.washer_status:
        friendly_name: Washer Status
        icon: mdi:washing-machine

      binary_sensor.dryer_state:
        icon: mdi:tumble-dryer
      binary_sensor.washer_state:
        icon: mdi:washing-machine
      sensor.dryer_status:
        friendly_name: Dryer Status
        icon: mdi:tumble-dryer
      binary_sensor.dryer_door:
        icon: mdi:tumble-dryer

      binary_sensor.high_water:
        friendly_name: Sink Level
        icon: mdi:water
      script.water_warning:
        icon: mdi:water-off

binary_sensor:

  - platform: template
    sensors:
      washer_state:
        friendly_name: "Washer State"
        device_class: running
        value_template: >-
          {% if is_state('input_select.washer_state', 'Washing')   %}
            on
          {% else %}
            off
          {% endif %}

    # binary_sensor.dryer_state is defined in the ESPHome laundry device

input_select:
  washer_status:
    name: Washer Status
    options:
      - Idle
      - Washing
      - Clean

  dryer_status:
    name: Dryer Status
    options:
      - Idle
      - Running
      - Cycle Complete

sensor:

  - platform: template
    sensors:
      washer_status:
        value_template: >-
          {% if is_state("binary_sensor.washer_lid_contact", "off") %}
            {{ states('input_select.washer_status') }}
          {% else %}
            Lid Open
          {% endif %}

  - platform: template
    sensors:
      dryer_status:
        value_template: >-
          {% if is_state("binary_sensor.dryer_door", "off") %}
            {{ states('input_select.dryer_status') }}
          {% else %}
            Door Open
          {% endif %}

automation:

#------------------ W A S H E R ---------------------------------------------------------------------------------------#

  - alias: Washer Start

    trigger:
      platform: numeric_state
      entity_id: sensor.washer_current
      above: 0.03
      for:
        hours: 0
        minutes: 0
        seconds: 10

    condition:
      - condition: state
        entity_id: binary_sensor.washer_state
        state: 'off'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washer_status
          option: Washing

  - alias: Washer Stop

    trigger:
      platform: numeric_state
      entity_id: sensor.washer_current
      below: 0.03
      for:
        hours: 0
        minutes: 2
        seconds: 30

    condition:
      - condition: state
        entity_id: binary_sensor.washer_state
        state: 'on'

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washer_status
          option: Clean

  - alias: Washer Lid Opens While Clean

    trigger:
      - platform: state
        entity_id: binary_sensor.washer_lid_contact
        from: "off"
        to: "on"
        for:
          hours: 0
          minutes: 0
          seconds: 8

    condition:
      - condition: state
        entity_id: binary_sensor.washer_state
        state: 'off'
      - condition: state
        entity_id: input_select.washer_status
        state: Clean

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.washer_status
          option: Idle

# Announcement

  - alias: 'Washer has stopped'
    trigger:
      - platform: state
        entity_id: input_boolean.washer_status
        from: 'on'
        to: 'off'
        for:
          hours: 0
          minutes: 0
          seconds: 0
    condition:
      condition: state
      entity_id: input_boolean.tts_automations
      state: "on"
    action:
      - service: notify.no_bedrooms_cloud
        data:
          message: >
            {{
              [
                "The washer has stopped",
                "Better get those clothes into the dryer",
                "Done washing"
              ] | random
            }}

#-------------------- D R Y E R ---------------------------------------------------------------------------------------#

  - alias: Dryer Vibration Detected
    trigger:
      - platform: state
        entity_id: binary_sensor.dryer_state
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: binary_sensor.dryer_door
        state: "off"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_status
          option: Running

  - alias: Dryer Vibration Stops - Door Closed
    trigger:
      - platform: state
        entity_id: binary_sensor.dryer_state
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: binary_sensor.dryer_door
        state: "off"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_status
          option: Cycle Complete

  - alias: Dryer Vibration Stops - Door Oopen
    trigger:
      - platform: state
        entity_id: binary_sensor.dryer_state
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: binary_sensor.dryer_door
        state: "on"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_status
          option: Idle

  - alias: Dryer Door Opens
    trigger:
      - platform: state
        entity_id: binary_sensor.dryer_door
        from: "off"
        to: "on"
        for:
          hours: 0
          minutes: 0
          seconds: 10
    condition:
      - condition: state
        entity_id: binary_sensor.dryer_state
        state: "off"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.dryer_status
          option: Idle

# Announcement

  - alias: 'Dryer has stopped'
    trigger:
      - platform: state
        entity_id: input_select.dryer_status
        from: Running
        to: Cycle Complete
        for:
          hours: 0
          minutes: 0
          seconds: 0
    condition:
      - condition: state
        entity_id: input_boolean.tts_automations
        state: "on"
      - condition: state
        entity_id: binary_sensor.dryer_door
        state: "off"
    action:
      - service: notify.no_bedrooms_cloud
        data:
          message: >
            {{
              [
                "The dryer has stopped",
                "Your laundry is dry",
                "The clothing dehydration process has terminated",
                "Hey everybody!  Let's empty the dryer!",
                "It's folding time..."
              ] | random
            }}

#------------------ H I G H  W A T E R --------------------------------------------------------------------------------#

  - alias: 'Laundry sink level high'
    trigger:
      platform: state
      entity_id: binary_sensor.high_water
      from: 'off'
      to: 'on'
      for:
        seconds: 5
    condition:
      - condition: state
        entity_id: script.water_warning
        state: 'off'
    action:
    - service: script.turn_on
      entity_id: script.water_warning

  - alias: 'Laundry sink level back to normal'
    trigger:
      platform: state
      entity_id: binary_sensor.high_water
      from: 'on'
      to: 'off'
      for:
        seconds: 5
    action:
    - service: script.turn_off
      entity_id: script.water_warning
    - service: light.turn_on
      entity_id: light.clock_circle
      data:
        effect: 'Clock'
    - service: light.turn_on
      entity_id: light.wall_clock
      data:
        effect: 'Clock'

script:
  water_warning:
    alias: High Water Warning
    sequence:
    - service: switch.turn_off
      entity_id: switch.washer
    - service: switch.toggle
      entity_id: switch.laundry_light
    - service: notify.all_speakers
      data:
        message: 'Warning! The lawndry sink water level is high! The washer has been turned off.'
    - service: light.turn_on
      entity_id: light.clock_circle
      data:
        effect: 'Police 3'
        brightness: 255
    - service: light.turn_on
      entity_id: light.wall_clock
      data:
        effect: 'Police 3'
        brightness: 255
    - delay:
        milliseconds: 250
    - service: switch.toggle
      entity_id: switch.laundry_light
    - service: light.toggle
      target:
        entity_id: light.living_room_lights
      data:
        transition: 0
    - delay:
        milliseconds: 250
    - service: switch.toggle
      entity_id: switch.laundry_light
    - service: light.toggle
      target:
        entity_id: light.living_room_lights
      data:
        transition: 0
    - delay:
        milliseconds: 250
    - service: switch.toggle
      entity_id: switch.laundry_light
    - service: light.toggle
      target:
        entity_id: light.living_room_lights
      data:
        transition: 0
    - delay:
        milliseconds: 250
    - service: switch.toggle
      entity_id: switch.laundry_light
    - service: light.toggle
      target:
        entity_id: light.living_room_lights
      data:
        transition: 0
    - delay:
        milliseconds: 250
    - service: switch.toggle
      entity_id: switch.laundry_light
    - service: light.toggle
      target:
        entity_id: light.living_room_lights
      data:
        transition: 0
    - delay:
        milliseconds: 250
    - service: switch.toggle
      entity_id: switch.laundry_light
    - service: light.toggle
      target:
        entity_id: light.living_room_lights
      data:
        transition: 0
    - delay:
        milliseconds: 250
    - service: switch.toggle
      entity_id: switch.laundry_light
    - service: light.toggle
      target:
        entity_id: light.living_room_lights
      data:
        transition: 0
    - delay:
        milliseconds: 250
    - service: switch.toggle
      entity_id: switch.laundry_light
    - service: light.toggle
      target:
        entity_id: light.living_room_lights
      data:
        transition: 0
    - delay:
        milliseconds: 250
    - service: switch.toggle
      entity_id: switch.laundry_light
    - service: light.toggle
      target:
        entity_id: light.living_room_lights
      data:
        transition: 0

