homeassistant:
  customize:
    light.workshop_light_1:
      friendly_name: Workshop Light 1
    binary_sensor.mm_wave_3_occupancy:
      friendly_name: Workshop Occupancy
      icon: mdi:hammer-wrench
    sensor.shellybutton1_3c6105e53723_battery:
      friendly_name: Workshop Lights Button Battery
    timer.workshop_lights:
      friendly_name: Workshop Lights Timer
    binary_sensor.workshop_motion_occupancy:
      friendly_name: Workshop Motion

light:

  - platform: group
    name: Workshop Lights
    unique_id: Workshop Lights
    entities:
      - light.workshop_light_1

timer:
  workshop_lights:
    duration: "00:20:01"
    icon: mdi:timer-outline
    restore: true

automation:

  # Workshop

  - alias: 'Workshop Lights Timer Start'
    trigger:
      platform: state
      entity_id: light.workshop_lights
      to: 'on'
    action:
      - service: timer.start
        entity_id: timer.workshop_lights

  - alias: 'Workshop Lights Timer Cancel'
    trigger:
      platform: state
      entity_id: light.workshop_lights
      to: 'off'
    action:
      - service: timer.cancel
        entity_id: timer.workshop_lights

  - alias: Workshop Lights Timer Restart on Motion
    ## motion restarts workshop lights timer

    trigger:
      - platform: state
        entity_id: binary_sensor.workshop_motion_occupancy
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.mm_wave_3_occupancy
        to: 'on'
        for:
          hours: 0
          minutes: 0
          seconds: 3
    condition:
      - condition: state
        entity_id: light.workshop_lights
        state: 'on'
    action:
      - service: timer.start
        entity_id: timer.workshop_lights

  - id: workshop_motion
    alias: Workshop motion turns on lights
    trigger:
      platform: state
      entity_id: binary_sensor.workshop_motion_occupancy
      from: 'off'
      to: 'on'
    action:
      service: light.turn_on
      entity_id: light.workshop_lights

  - alias: "Workshop occupancy turns on lights"
    trigger:
      - platform: state
        entity_id: binary_sensor.mm_wave_3_occupancy
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.workshop_lights

  - alias: "Workshop lights timer turns off lights"
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.workshop_lights
    condition:
      condition: and
      conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.mm_wave_3_occupancy
          state: 'off'
        - condition: state
          entity_id: binary_sensor.mm_wave_3_occupancy
          state: 'Unavailable'
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.workshop_motion_occupancy
          state: 'off'
        - condition: state
          entity_id: binary_sensor.workshop_motion_occupancy
          state: 'Unavailable'
      - condition: state
        entity_id: input_boolean.lights_off_automations
        state: "on"
    action:
        - service: light.turn_off
          entity_id: light.workshop_lights

  - alias: "Workshop lights timer does restart"
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.workshop_lights
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.mm_wave_3_occupancy
          state: 'on'
        - condition: state
          entity_id: binary_sensor.workshop_motion_occupancy
          state: 'on'
    action:
      - service: timer.start
        entity_id: timer.workshop_lights

#-----------------------------------------------------------#

  - id: workshop_temp_min_reached
    alias: "Workshop Temperature Minimum Reached"
    description: 'Notify when the workshop temp is above the minimum'
    trigger:
      - platform: numeric_state
        entity_id: sensor.workshop_h5100_403b_temperature
        above: 50
    condition:
      - condition: time
        after: '09:00:00'
        before: '20:00:00'
    action:
      - service: notify.no_bedrooms_cloud
        data:
          message: 'The workshop has reached minimum temperature'
